// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_WEB']!,
    appId: '1:159501230908:web:9ad3ec184dfb7cd711b439',
    messagingSenderId: '159501230908',
    projectId: 'academe-c9ea5',
    authDomain: 'academe-c9ea5.firebaseapp.com',
    storageBucket: 'academe-c9ea5.firebasestorage.app',
    measurementId: 'G-LVF851E4M5',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_WEB']!,
    appId: '1:159501230908:android:f9d3ed7c17c9b6e411b439',
    messagingSenderId: '159501230908',
    projectId: 'academe-c9ea5',
    storageBucket: 'academe-c9ea5.firebasestorage.app',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_IOS']!,
    appId: '1:159501230908:ios:fcfbc8f031250b0811b439',
    messagingSenderId: '159501230908',
    projectId: 'academe-c9ea5',
    storageBucket: 'academe-c9ea5.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static final FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_MACOS']!,
    appId: '1:159501230908:ios:fcfbc8f031250b0811b439',
    messagingSenderId: '159501230908',
    projectId: 'academe-c9ea5',
    storageBucket: 'academe-c9ea5.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static final FirebaseOptions windows = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_WINDOWS']!,
    appId: '1:159501230908:web:3f62fcc544aca76111b439',
    messagingSenderId: '159501230908',
    projectId: 'academe-c9ea5',
    authDomain: 'academe-c9ea5.firebaseapp.com',
    storageBucket: 'academe-c9ea5.firebasestorage.app',
    measurementId: 'G-QKR23L9H1S',
  );
}
